"""init_final

Revision ID: 046687ff9488
Revises: 
Create Date: 2025-11-12 12:49:01.331936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '046687ff9488'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('dev_color', sa.String(length=32), nullable=True),
    sa.Column('demo_color', sa.String(length=32), nullable=True),
    sa.Column('lt_color', sa.String(length=32), nullable=True),
    sa.Column('prod_color', sa.String(length=32), nullable=True),
    sa.Column('dev_status', sa.String(length=64), nullable=True),
    sa.Column('demo_status', sa.String(length=64), nullable=True),
    sa.Column('lt_status', sa.String(length=64), nullable=True),
    sa.Column('prod_status', sa.String(length=64), nullable=True),
    sa.Column('orphan_notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignments_task_id'), 'assignments', ['task_id'], unique=False)
    op.create_table('jira_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jira_items_task_id'), 'jira_items', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jira_items_task_id'), table_name='jira_items')
    op.drop_table('jira_items')
    op.drop_index(op.f('ix_assignments_task_id'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_table('tasks')
    op.drop_table('people')
    # ### end Alembic commands ###
